# Robot fleet configuration for ROS2 Agent
# Active robots will be initialized on startup

robots:
  - id: drone
    type: drone
    namespace: /drone
    initialized: false
    active: false
    topics:
      pose: /drone/mavros/local_position/pose
      battery: /drone/mavros/battery
      camera: /drone/gimbal_camera
      cmd_vel: /drone/mavros/setpoint_velocity/cmd_vel
      gimbal_pitch: /drone/gimbal/cmd_pitch
      gimbal_roll: /drone/gimbal/cmd_roll
      gimbal_yaw: /drone/gimbal/cmd_yaw
      imu_gimbal: /drone/imu_gimbal
      setpoint_position: /drone/mavros/setpoint_position/local
      state: /drone/mavros/state
      altitude: /drone/mavros/altitude
      vfr_hud: /drone/mavros/vfr_hud
      global_position: /drone/mavros/global_position/global
      local_position: /drone/mavros/local_position/pose
      scan: /drone/scan
      scan_points: /drone/scan/points
      imu: /drone/mavros/imu/data
      extended_state: /drone/mavros/extended_state
      home_position: /drone/mavros/home_position/home
    services:
      arming: /drone/mavros/cmd/arming
      set_mode: /drone/mavros/set_mode
      set_home: /drone/mavros/home_position/set

  # Wheeled robot - commented out for now
  # - id: wheeled1
  #   type: wheeled
  #   namespace: /wheeled1
  #   initialized: false
  #   active: false
  #   topics:
  #     pose: /wheeled1/odom
  #     battery: /wheeled1/battery_state
  #     camera: /wheeled1/camera/image_raw
  #     cmd_vel: /wheeled1/cmd_vel
  #     scan: /wheeled1/scan
  #   services:
  #     enable_motors: /wheeled1/enable_motors

  # Legged robot - commented out for now  
  # - id: legged1
  #   type: legged
  #   namespace: /legged1
  #   initialized: false
  #   active: false
  #   topics:
  #     pose: /legged1/state/odom
  #     battery: /legged1/state/battery
  #     camera: /legged1/camera/image_raw
  #     cmd_vel: /legged1/cmd_vel
  #   services:
  #     stand: /legged1/stand_cmd
  #     sit: /legged1/sit_cmd