# Check your drone_px4_pluginlists.yaml - GPS should NOT be in the denylist

/drone/mavros/**:
  ros__parameters:
    plugin_denylist:
      # ✅ IMPORTANT: Make sure 'global_position' is NOT in this list
      # ✅ IMPORTANT: Make sure 'gps' is NOT in this list
      
      # These should be denylisted (as you have):
      - image_pub
      - vibration
      - distance_sensor
      - rangefinder
      - wheel_odometry
      - mount_control
      - log_transfer
      - landing_target
      - gps_rtk          # ✅ This is OK - RTK GPS (different from basic GPS)
      - manual_control
      - hil
      - adsb
      - optical_flow
      - terrain
      - ftp
      - tdr_radio
      - rallypoint
      - obstacle
      - cellular_status
      - actuator_control
      - fake_gps         # ✅ This is OK - fake GPS (different from navsat GPS)
      - esc_telemetry
      - mag_calibration
      - px4flow
      - esc_status
      - gps_input        # ✅ This is OK - GPS input (different from navsat GPS)
      - debug_value
      - geofence
      - nav_controller_output
      - wind
      - play_tune
      - camera
      - guided_target
      # - mocap

    # ✅ IMPORTANT: Make sure global_position plugin is enabled (not in denylist above)